CREATE PROCEDURE STUDY2(
    @MODE INT
)
AS
BEGIN
    SET NOCOUNT ON;
    IF @MODE = 0
    BEGIN
        SELECT * FROM TBL_ORDER
    END
    ELSE IF @MODE = 1
     BEGIN
        UPDATE TBL_ORDER SET USERNO = 5 WHERE USERNO = 1
     END
     ELSE
     BEGIN
        DELETE FROM TBL_ORDER WHERE USERNO = 5 
     END
END