CREATE PROCEDURE RESULT_DAY_INSERT
(
    @INFO NVARCHAR(200)
) AS
BEGIN

DECLARE @NEXT_RESULTNO INT, @PRICESUM INT, @TEMPINFO NVARCHAR(400);


SET NOCOUNT ON;

SELECT @NEXT_RESULTNO = (SELECT ISNULL(MAX(RESULTNO) + 1, 0) FROM TBL_RESULTDAY);
SELECT @PRICESUM = SUM(PRICE) FROM TBL_ORDER

INSERT INTO TBL_RESULTDAY(RESULTNO, PRICESUM,RESULTDAY)
VALUES(  
    @NEXT_RESULTNO,
    @PRICESUM,
    GETDATE()
);

SET @TEMPINFO = @INFO+N' 데이터가 들어갔습니다.';
SELECT @TEMPINFO, @NEXT_RESULTNO, @PRICESUM 

END